package config

import (
	_ "embed"
	"strings"
	"sync"
)

// claudeEnvFile contains the embedded claude-usage.env file.
// This file is auto-generated by scripts/extract-claude-config.sh
// and contains public configuration values extracted from the Claude CLI.
//
//go:embed claude-usage.env
var claudeEnvFile string

var (
	claudeConfig     map[string]string
	claudeConfigOnce sync.Once
)

// parseEnvFile parses the embedded env file into a map.
func parseEnvFile(content string) map[string]string {
	result := make(map[string]string)
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimSpace(line)
		// Skip empty lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Parse KEY=VALUE
		if idx := strings.Index(line, "="); idx > 0 {
			key := strings.TrimSpace(line[:idx])
			value := strings.TrimSpace(line[idx+1:])
			result[key] = value
		}
	}
	return result
}

// getClaudeConfig returns the parsed config, initializing it lazily.
func getClaudeConfig() map[string]string {
	claudeConfigOnce.Do(func() {
		claudeConfig = parseEnvFile(claudeEnvFile)
	})
	return claudeConfig
}

// getConfigOrDefault returns a config value or the default if not found.
func getConfigOrDefault(key, defaultValue string) string {
	config := getClaudeConfig()
	if val, ok := config[key]; ok && val != "" {
		return val
	}
	return defaultValue
}

// GetClaudeVersion returns the Claude CLI version.
func GetClaudeVersion() string {
	return getConfigOrDefault("CLAUDE_VERSION", "2.1.27")
}

// GetClaudeClientID returns the OAuth client ID.
// This is a public identifier extracted from the Claude CLI binary.
func GetClaudeClientID() string {
	return getConfigOrDefault("CLAUDE_CLIENT_ID", "9d1c250a-e61b-44d9-88ed-5944d1962f5e")
}

// GetClaudeTokenEndpoint returns the OAuth token refresh endpoint.
func GetClaudeTokenEndpoint() string {
	return getConfigOrDefault("CLAUDE_TOKEN_ENDPOINT", "https://platform.claude.com/v1/oauth/token")
}

// GetClaudeUsageEndpoint returns the usage API endpoint.
func GetClaudeUsageEndpoint() string {
	return getConfigOrDefault("CLAUDE_USAGE_ENDPOINT", "https://api.anthropic.com/api/oauth/usage")
}

// GetClaudeAnthropicBeta returns the required anthropic-beta header value.
func GetClaudeAnthropicBeta() string {
	return getConfigOrDefault("CLAUDE_ANTHROPIC_BETA", "oauth-2025-04-20")
}

// GetClaudeOAuthScopes returns the OAuth scopes.
func GetClaudeOAuthScopes() string {
	return getConfigOrDefault("CLAUDE_OAUTH_SCOPES", "user:inference user:profile user:sessions:claude_code user:mcp_servers")
}

// GetClaudeUserAgent returns the User-Agent string for API requests.
func GetClaudeUserAgent() string {
	return "claude-code/" + GetClaudeVersion()
}

// GetUpdateURL returns the base URL for downloading updates.
// The full URL is constructed by appending the platform-specific binary name.
func GetUpdateURL() string {
	return getConfigOrDefault("CLAUDE_UPDATE_URL", "")
}
